# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emerald
email: smilemaple1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is Iola Lin. I come frome Taiwan. This is my personal site with a default jekyll template. 
  I'm trying to go through building this site from the most simple part. Welcome to discuss with me about blogging.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iola-lin.github.io" # the base hostname & protocol for your site
github_username:  iola-lin

# Build settings
highlighter: rouge
markdown: kramdown

site_id: iola-lin.github.io

comments : true

theme: jekyll-theme-tactile